# Generated by Django 5.2.10 on 2026-02-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="participatns",
            new_name="participants",
        ),
    ]
